# Standard Scaling
* Implement standard scaling using sklearn. This should always be done for distance based algorithms such as KNN, SVM, and clustering as well as regularization techniques such as Lasso and Ridge regression. This can also help models using gradient descent to converge, examples include Linear Regression, Logistic Regression, and Neural Networks

In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
# Generate random data with each column being on different scales
np.random.seed(42)
data = np.random.rand(100, 5) * [1000, 100, 10, 1, .1]

In [3]:
print("Original Data:")
print(np.array2string(data, precision = 3))

Original Data:
[[3.745e+02 9.507e+01 7.320e+00 5.987e-01 1.560e-02]
 [1.560e+02 5.808e+00 8.662e+00 6.011e-01 7.081e-02]
 [2.058e+01 9.699e+01 8.324e+00 2.123e-01 1.818e-02]
 [1.834e+02 3.042e+01 5.248e+00 4.319e-01 2.912e-02]
 [6.119e+02 1.395e+01 2.921e+00 3.664e-01 4.561e-02]
 [7.852e+02 1.997e+01 5.142e+00 5.924e-01 4.645e-03]
 [6.075e+02 1.705e+01 6.505e-01 9.489e-01 9.656e-02]
 [8.084e+02 3.046e+01 9.767e-01 6.842e-01 4.402e-02]
 [1.220e+02 4.952e+01 3.439e-01 9.093e-01 2.588e-02]
 [6.625e+02 3.117e+01 5.201e+00 5.467e-01 1.849e-02]
 [9.696e+02 7.751e+01 9.395e+00 8.948e-01 5.979e-02]
 [9.219e+02 8.849e+00 1.960e+00 4.523e-02 3.253e-02]
 [3.887e+02 2.713e+01 8.287e+00 3.568e-01 2.809e-02]
 [5.427e+02 1.409e+01 8.022e+00 7.455e-02 9.869e-02]
 [7.722e+02 1.987e+01 5.522e-02 8.155e-01 7.069e-02]
 [7.290e+02 7.713e+01 7.404e-01 3.585e-01 1.159e-02]
 [8.631e+02 6.233e+01 3.309e+00 6.356e-02 3.110e-02]
 [3.252e+02 7.296e+01 6.376e+00 8.872e-01 4.722e-02]
 [1.196e+02 7.132e+01 7.608e+00

In [4]:
# Create standard scaler object and fit it to the original data
scaler = StandardScaler()
scaler.fit(data)

StandardScaler()

In [5]:
# Transform the data
scaled_data = scaler.transform(data)

In [6]:
print("Scaled Data:")
print(np.array2string(scaled_data, precision = 3))

Scaled Data:
[[-0.44   1.426  0.833  0.265 -0.972]
 [-1.178 -1.566  1.29   0.274  0.829]
 [-1.636  1.49   1.175 -1.059 -0.887]
 [-1.086 -0.741  0.126 -0.306 -0.531]
 [ 0.362 -1.293 -0.667 -0.531  0.007]
 [ 0.948 -1.091  0.09   0.244 -1.329]
 [ 0.347 -1.189 -1.441  1.466  1.669]
 [ 1.026 -0.739 -1.33   0.559 -0.045]
 [-1.293 -0.101 -1.545  1.33  -0.636]
 [ 0.533 -0.716  0.11   0.087 -0.878]
 [ 1.571  0.837  1.54   1.28   0.47 ]
 [ 1.409 -1.464 -0.994 -1.632 -0.419]
 [-0.392 -0.851  1.163 -0.564 -0.564]
 [ 0.128 -1.288  1.072 -1.531  1.738]
 [ 0.904 -1.094 -1.644  1.008  0.825]
 [ 0.758  0.825 -1.41  -0.558 -1.103]
 [ 1.211  0.329 -0.535 -1.569 -0.466]
 [-0.607  0.685  0.511  1.254  0.06 ]
 [-1.301  0.63   0.931  0.137  1.034]
 [-0.037 -0.008 -0.205 -1.7   -1.129]
 [-1.599  0.373 -0.591 -0.043  1.48 ]
 [-0.863 -0.385  0.913 -1.002 -1.229]
 [-0.726 -1.22   1.507  0.983  0.585]
 [ 1.239  0.933 -1.027  1.273  0.279]
 [ 1.023  1.243 -0.578 -1.409 -0.737]
 [-0.262  0.981  1.272 -1.763  0.185]